name: C/C++ CI

on:
  push:
    branches: [ "autoconf_automake" ]
  pull_request:
    branches: [ "autoconf_automake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install bison flex
    - name: configure
    - name: Setup linux environment
      if: matrix.env.platform == 'linux'
      run: |
         sudo apt update
         # flex-old contains FlexLexer.h which is needed by util
         # For some reason, flex does not contain this header
         sudo apt install --yes git cmake libboost-all-dev expat zlib1g libboost-all-dev autotools-dev autopoint autoconf help2man libwxgtk3.0-gtk3-dev
    - name: Install flex
      if: matrix.env.platform == 'linux'
      run: |
         # The new flex version in ubuntu does not have the needed FlexLexer.h
         # but the older version has problems to create files
         git clone https://github.com/westes/flex.git
         cd flex
         ./autogen.sh
         ./configure
         make
         sudo make install
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
