name: C/C++ CI

on:
  push:
    branches: [ "autoconf_automake" ]
  pull_request:
    branches: [ "autoconf_automake" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: find flexlexer.h
      run:  find / -name FlexLexer.h
    - name: autgen.sh
      run:  ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
